os: osx
osx_image: xcode12.2

xcode_project: Caoculadora.xcodeproj
xcode_scheme: Caoculadora
xcode_destination: platform=iOS Simulator,name=iPhone 11

before_install:
  - rvm install 2.7.2
  - bundle update

# jobs and stages to run
jobs:
  include:
    - stage: "Beta Deploy"
      name: "Deploy to TestFlight"
      script:
        - echo "machine github.com login $GITHUB_API_TOKEN" >> ~/.netrc
        - bundle exec fastlane beta