# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:

    macos:
      xcode: 12.4.0 # Specify the Xcode version to use

    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: beta

    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan